### ISSUE TITLE
Error when running `make` or `test-local.sh`

### ISSUE THREAD

**Issue by sosthene-nitrokey** [Nitrokey/nitrokey-3-tests#15]
```
14:10:/h/s/C/nitrokey-3-tests/ main>./test-local.sh ../nitrokey-3-firmware
    Finished release [optimized + debuginfo] target(s) in 0.08s
'../nitrokey-3-firmware/target/release/usbip-runner' -> 'bin/usbip-runner'
    Finished release [optimized + debuginfo] target(s) in 0.08s
'../nitrokey-3-firmware/target/release/usbip-runner' -> 'bin/usbip-provisioner'
docker build . --tag nitrokey-3-tests --quiet
Emulate Docker CLI using podman. Create /etc/containers/nodocker to quiet msg.
  Running command git clone --filter=blob:none --quiet https://github.com/nitrokey/pynitrokey /tmp/pip-install-__fzbktg/pynitrokey_21bf396f7cbb4ea6a5343a06b1b25ba4
  Running command git rev-parse -q --verify 'sha^0e8bf844fd764807828cb6539e519170d5bb0be5'
  Running command git fetch -q https://github.com/nitrokey/pynitrokey 0e8bf844fd764807828cb6539e519170d5bb0be5
  Running command git checkout -q 0e8bf844fd764807828cb6539e519170d5bb0be5
  error: subprocess-exited-with-error
  
  × pip subprocess to install backend dependencies did not run successfully.
  │ exit code: 2
  ╰─> [181 lines of output]
      Collecting urllib3
        Downloading urllib3-1.26.13-py2.py3-none-any.whl (140 kB)
           ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 140.6/140.6 kB 4.3 MB/s eta 0:00:00
      Collecting intelhex
        Downloading intelhex-2.3.0-py2.py3-none-any.whl (50 kB)
           ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 50.9/50.9 kB 18.0 MB/s eta 0:00:00
      Collecting python-dateutil
        Downloading python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
           ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 247.7/247.7 kB 13.6 MB/s eta 0:00:00
      Collecting requests
        Downloading requests-2.28.1-py3-none-any.whl (62 kB)
           ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.8/62.8 kB 32.3 MB/s eta 0:00:00
      Collecting cryptography<37,>=3.4.4
        Downloading cryptography-36.0.2-cp36-abi3-manylinux_2_24_x86_64.whl (3.6 MB)
           ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.6/3.6 MB 27.1 MB/s eta 0:00:00
      Collecting spsdk<1.8.0,>=1.7.0
        Downloading spsdk-1.7.1-py3-none-any.whl (684 kB)
           ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 684.7/684.7 kB 27.1 MB/s eta 0:00:00
      Collecting nkdfu
        Downloading nkdfu-0.2-py3-none-any.whl (16 kB)
      Collecting fido2<2,>=1.1.0
        Downloading fido2-1.1.0-py3-none-any.whl (201 kB)
           ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 201.1/201.1 kB 45.7 MB/s eta 0:00:00
      Collecting cffi
        Downloading cffi-1.15.1-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (441 kB)
           ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 441.2/441.2 kB 62.1 MB/s eta 0:00:00
      Collecting nrfutil<7,>=6.1.4
        Downloading nrfutil-6.1.7.tar.gz (845 kB)
           ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 845.3/845.3 kB 35.0 MB/s eta 0:00:00
        Preparing metadata (setup.py): started
        Preparing metadata (setup.py): finished with status 'done'
      Collecting tqdm
        Downloading tqdm-4.64.1-py2.py3-none-any.whl (78 kB)
           ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 78.5/78.5 kB 30.2 MB/s eta 0:00:00
      Collecting ecdsa
        Downloading ecdsa-0.18.0-py2.py3-none-any.whl (142 kB)
           ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 142.9/142.9 kB 44.6 MB/s eta 0:00:00
      Collecting click<9,>=8.0.0
        Downloading click-8.1.3-py3-none-any.whl (96 kB)
           ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 96.6/96.6 kB 50.6 MB/s eta 0:00:00
      Collecting pyusb
        Downloading pyusb-1.2.1-py3-none-any.whl (58 kB)
           ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 58.4/58.4 kB 37.0 MB/s eta 0:00:00
      Collecting tlv8
        Downloading tlv8-0.10.0.tar.gz (16 kB)
        Preparing metadata (setup.py): started
        Preparing metadata (setup.py): finished with status 'done'
      Collecting six>=1.5
        Downloading six-1.16.0-py2.py3-none-any.whl (11 kB)
      Collecting certifi>=2017.4.17
        Downloading certifi-2022.12.7-py3-none-any.whl (155 kB)
           ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 155.3/155.3 kB 40.6 MB/s eta 0:00:00
      Collecting idna<4,>=2.5
        Downloading idna-3.4-py3-none-any.whl (61 kB)
           ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.5/61.5 kB 34.7 MB/s eta 0:00:00
      Collecting charset-normalizer<3,>=2
        Downloading charset_normalizer-2.1.1-py3-none-any.whl (39 kB)
      Collecting cmsis-pack-manager<0.3.0
        Downloading cmsis_pack_manager-0.2.10-py2.py3-none-manylinux1_x86_64.whl (25.1 MB)
           ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 25.1/25.1 MB 49.2 MB/s eta 0:00:00
      Collecting pylink-square<0.11.9,>=0.8.2
        Downloading pylink_square-0.11.1-py2.py3-none-any.whl (78 kB)
           ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 78.4/78.4 kB 41.0 MB/s eta 0:00:00
      Collecting click-option-group<0.6,>=0.3.0
        Downloading click_option_group-0.5.5-py3-none-any.whl (12 kB)
      Collecting astunparse<2,>=1.6
        Downloading astunparse-1.6.3-py2.py3-none-any.whl (12 kB)
      Collecting bincopy<17.11,>=17.10.2
        Downloading bincopy-17.10.3-py3-none-any.whl (17 kB)
      Collecting pyocd-pemicro<1.2.0,>=1.1.1
        Downloading pyocd_pemicro-1.1.3-py3-none-any.whl (8.9 kB)
      Collecting deepmerge==0.3.0
        Downloading deepmerge-0.3.0-py2.py3-none-any.whl (7.6 kB)
      Collecting pycryptodome<4,>=3.9.3
        Downloading pycryptodome-3.16.0-cp35-abi3-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (2.3 MB)
           ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.3/2.3 MB 53.7 MB/s eta 0:00:00
      Collecting commentjson<1,>=0.9
        Downloading commentjson-0.9.0.tar.gz (8.7 kB)
        Preparing metadata (setup.py): started
        Preparing metadata (setup.py): finished with status 'done'
      Collecting crcmod==1.7
        Downloading crcmod-1.7.tar.gz (89 kB)
           ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 89.7/89.7 kB 29.6 MB/s eta 0:00:00
        Preparing metadata (setup.py): started
        Preparing metadata (setup.py): finished with status 'done'
      Collecting hexdump~=3.3
        Downloading hexdump-3.3.zip (12 kB)
        Preparing metadata (setup.py): started
        Preparing metadata (setup.py): finished with status 'done'
      Collecting sly==0.4
        Downloading sly-0.4.tar.gz (60 kB)
           ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.6/60.6 kB 15.8 MB/s eta 0:00:00
        Preparing metadata (setup.py): started
        Preparing metadata (setup.py): finished with status 'done'
      Collecting pyocd<=0.31.0,>=0.28.3
        Downloading pyocd-0.31.0-py3-none-any.whl (12.5 MB)
           ━━━━━━━━━━━━━━━━━━━━                     6.3/12.5 MB 59.5 MB/s eta 0:00:01
      ERROR: Exception:
      Traceback (most recent call last):
        File "/venv/lib/python3.9/site-packages/pip/_vendor/urllib3/response.py", line 437, in _error_catcher
          yield
        File "/venv/lib/python3.9/site-packages/pip/_vendor/urllib3/response.py", line 560, in read
          data = self._fp_read(amt) if not fp_closed else b""
        File "/venv/lib/python3.9/site-packages/pip/_vendor/urllib3/response.py", line 526, in _fp_read
          return self._fp.read(amt) if amt is not None else self._fp.read()
        File "/venv/lib/python3.9/site-packages/pip/_vendor/cachecontrol/filewrapper.py", line 90, in read
          data = self.__fp.read(amt)
        File "/usr/lib/python3.9/http/client.py", line 458, in read
          n = self.readinto(b)
        File "/usr/lib/python3.9/http/client.py", line 502, in readinto
          n = self.fp.readinto(b)
        File "/usr/lib/python3.9/socket.py", line 704, in readinto
          return self._sock.recv_into(b)
        File "/usr/lib/python3.9/ssl.py", line 1241, in recv_into
          return self.read(nbytes, buffer)
        File "/usr/lib/python3.9/ssl.py", line 1099, in read
          return self._sslobj.read(len, buffer)
      socket.timeout: The read operation timed out
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "/venv/lib/python3.9/site-packages/pip/_internal/cli/base_command.py", line 160, in exc_logging_wrapper
          status = run_func(*args)
        File "/venv/lib/python3.9/site-packages/pip/_internal/cli/req_command.py", line 247, in wrapper
          return func(self, options, args)
        File "/venv/lib/python3.9/site-packages/pip/_internal/commands/install.py", line 400, in run
          requirement_set = resolver.resolve(
        File "/venv/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 92, in resolve
          result = self._result = resolver.resolve(
        File "/venv/lib/python3.9/site-packages/pip/_vendor/resolvelib/resolvers.py", line 481, in resolve
          state = resolution.resolve(requirements, max_rounds=max_rounds)
        File "/venv/lib/python3.9/site-packages/pip/_vendor/resolvelib/resolvers.py", line 373, in resolve
          failure_causes = self._attempt_to_pin_criterion(name)
        File "/venv/lib/python3.9/site-packages/pip/_vendor/resolvelib/resolvers.py", line 213, in _attempt_to_pin_criterion
          criteria = self._get_updated_criteria(candidate)
        File "/venv/lib/python3.9/site-packages/pip/_vendor/resolvelib/resolvers.py", line 204, in _get_updated_criteria
          self._add_to_criteria(criteria, requirement, parent=candidate)
        File "/venv/lib/python3.9/site-packages/pip/_vendor/resolvelib/resolvers.py", line 172, in _add_to_criteria
          if not criterion.candidates:
        File "/venv/lib/python3.9/site-packages/pip/_vendor/resolvelib/structs.py", line 151, in __bool__
          return bool(self._sequence)
        File "/venv/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 155, in __bool__
          return any(self)
        File "/venv/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 143, in <genexpr>
          return (c for c in iterator if id(c) not in self._incompatible_ids)
        File "/venv/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 47, in _iter_built
          candidate = func()
        File "/venv/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 206, in _make_candidate_from_link
          self._link_candidate_cache[link] = LinkCandidate(
        File "/venv/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 297, in __init__
          super().__init__(
        File "/venv/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 162, in __init__
          self.dist = self._prepare()
        File "/venv/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 231, in _prepare
          dist = self._prepare_distribution()
        File "/venv/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 308, in _prepare_distribution
          return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
        File "/venv/lib/python3.9/site-packages/pip/_internal/operations/prepare.py", line 491, in prepare_linked_requirement
          return self._prepare_linked_requirement(req, parallel_builds)
        File "/venv/lib/python3.9/site-packages/pip/_internal/operations/prepare.py", line 536, in _prepare_linked_requirement
          local_file = unpack_url(
        File "/venv/lib/python3.9/site-packages/pip/_internal/operations/prepare.py", line 166, in unpack_url
          file = get_http_url(
        File "/venv/lib/python3.9/site-packages/pip/_internal/operations/prepare.py", line 107, in get_http_url
          from_path, content_type = download(link, temp_dir.path)
        File "/venv/lib/python3.9/site-packages/pip/_internal/network/download.py", line 147, in __call__
          for chunk in chunks:
        File "/venv/lib/python3.9/site-packages/pip/_internal/cli/progress_bars.py", line 53, in _rich_progress_bar
          for chunk in iterable:
        File "/venv/lib/python3.9/site-packages/pip/_internal/network/utils.py", line 63, in response_chunks
          for chunk in response.raw.stream(
        File "/venv/lib/python3.9/site-packages/pip/_vendor/urllib3/response.py", line 621, in stream
          data = self.read(amt=amt, decode_content=decode_content)
        File "/venv/lib/python3.9/site-packages/pip/_vendor/urllib3/response.py", line 586, in read
          raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
        File "/usr/lib/python3.9/contextlib.py", line 135, in __exit__
          self.gen.throw(type, value, traceback)
        File "/venv/lib/python3.9/site-packages/pip/_vendor/urllib3/response.py", line 442, in _error_catcher
          raise ReadTimeoutError(self._pool, None, "Read timed out.")
      pip._vendor.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install backend dependencies did not run successfully.
│ exit code: 2
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
Error: building at STEP "RUN /venv/bin/pip install --requirement requirements.txt --progress-bar off": while running runtime: exit status 1
make: *** [Makefile:24: build-docker] Error 1
```

I am running it with podman instead of docker, but the connection error is weird.

**Comment by sosthene-nitrokey** [comment]
Rebooting solved the issue.
